services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    networks:
      pb-network:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "Pass@word"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    networks:
      pb-network:
      
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ./init.sql:/tmp/init.sql
      - ./init.sh:/tmp/init.sh
    command: /bin/bash ./tmp/init.sh
    networks:
      pb-network:
  
  webapi:
    container_name: webapi
    build:
      context: .
      dockerfile: src/services/Register/WebApi/Dockerfile
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:
      - sqlserver
      - rabbitmq
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=paranabanco;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;TrustServerCertificate=True;"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: "guest"
      RabbitMQ__Password: "guest"
    networks:
      pb-network:

  consumer1:
    build:
      context: .
      dockerfile: /src/services/CreditProposal/WebApi/Dockerfile
    depends_on:
      - consumer2
    restart: on-failure
    ports:
      - "5002:8080"
      - "5003:8081"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=paranabanco;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;TrustServerCertificate=True;"
      RabbitMQ__Host: "rabbitmq"
      RabbitMQ__Username: "guest"
      RabbitMQ__Password: "guest"
    networks:
      pb-network:
    
  consumer2:
    build:
      context: .
      dockerfile: /src/services/creditCard/WebApi/Dockerfile
    depends_on:
      - webapi
    restart: on-failure
    ports:
      - "5004:8080"
      - "5005:8081"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=paranabanco;User Id=sa;Password=Pass@word;MultipleActiveResultSets=True;TrustServerCertificate=True;"
      RabbitMQ__my-network: "rabbitmq"
      RabbitMQ__Username: "guest"
      RabbitMQ__Password: "guest"
    networks:
      pb-network:

networks:
  pb-network:
    driver: bridge
      